In [40]:
import numpy as np 
import pandas as pd 
import seaborn as sns
import plotly.express as px
from sklearn.preprocessing import StandardScaler, minmax_scale

In [41]:
df = px.data.gapminder()

In [42]:
df.head()

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,AFG,4
1,Afghanistan,Asia,1957,30.332,9240934,820.853030,AFG,4
2,Afghanistan,Asia,1962,31.997,10267083,853.100710,AFG,4
3,Afghanistan,Asia,1967,34.020,11537966,836.197138,AFG,4
4,Afghanistan,Asia,1972,36.088,13079460,739.981106,AFG,4

In [43]:
scaler = StandardScaler()

In [44]:
X = df[["lifeExp"	,"pop"	,"gdpPercap"]]
X.head()

   lifeExp       pop   gdpPercap
0   28.801   8425333  779.445314
1   30.332   9240934  820.853030
2   31.997  10267083  853.100710
3   34.020  11537966  836.197138
4   36.088  13079460  739.981106

In [45]:
X_scaled = scaler.fit_transform(X)

In [53]:
X_scaleds

array([[-2.37533395, -0.19953387, -0.65308656],
       [-2.25677417, -0.19184871, -0.64888468],
       [-2.1278375 , -0.18217962, -0.64561231],
       ...,
       [-0.98080452, -0.17145786, -0.6517669 ],
       [-1.5089415 , -0.16654284, -0.66398574],
       [-1.23805834, -0.16291906, -0.68451728]])

In [47]:
X.head(1)

   lifeExp      pop   gdpPercap
0   28.801  8425333  779.445314

In [48]:
scaler = minmax_scale(X)
scaler

array([[0.08816351, 0.00634398, 0.00475168],
       [0.11411091, 0.00696251, 0.00511721],
       [0.14232933, 0.0077407 , 0.00540187],
       ...,
       [0.39336316, 0.00860362, 0.00486648],
       [0.27777778, 0.0089992 , 0.00380354],
       [0.33706189, 0.00929085, 0.00201747]])